/**
 * Diagnóstico guardado 1ac7186c-2745-4b18-9de8-8781fd40fc98 (Snake Store,
 * versión 5, 2026-09-12), copiado tal cual está en la tabla `diagnostico`:
 * `datos`, `derivados`, `fugas` y `estados_bloque` sin tocar. Es anterior a las
 * preguntas "¿Tiene tienda propia?", "¿Pauta en Meta?" y "¿Pauta en Google?":
 * no trae `pauta_meta` ni `pauta_google`, y `canal_tienda_no_aplica` está en el
 * `false` que el formulario guardaba por defecto.
 */
import type { DatosDiagnostico } from "@/lib/diagnostico-form";
import type { Derivados, EstadosBloque, Fuga } from "@/lib/calculo-diagnostico";

export const CASO_1AC7186C = {
  id: "1ac7186c-2745-4b18-9de8-8781fd40fc98",
  modo: "A" as const,
  fecha: "2026-09-12",
  version: 5,
  estados_bloque: {
    cuenta: "sin_datos",
    economia: "sin_datos",
    medicion: "sin_datos",
    creativos: "rojo",
    funnel_web: "amarillo",
  } as unknown as EstadosBloque,
  datos: {
    pasarela: "mercado_pago",
    vertical: "indumentaria",
    plataforma: "tiendanube",
    capi_estado: "ausente",
    envio_bruto: null,
    tiene_pixel: false,
    canal_ml_pct: null,
    gasto_diario: null,
    descuento_pct: null,
    dolor_cliente: "No",
    nombre_tienda: "Snake Store",
    reparto_pauta: "",
    csv_ctr_global: null,
    inversion_meta: 0,
    ml_product_ads: null,
    ml_tiene_clips: null,
    canal_ml_moneda: "ARS",
    canal_ml_ticket: null,
    csv_gasto_total: null,
    plan_plataforma: "inicial",
    ticket_promedio: 225226,
    tiene_analytics: null,
    canal_ml_periodo: "mensual",
    canal_tienda_pct: null,
    csv_dias_periodo: null,
    inversion_google: 0,
    producto_1_costo: 40000,
    producto_2_costo: 35000,
    producto_3_costo: 20000,
    producto_4_costo: null,
    producto_5_costo: null,
    agregados_carrito: null,
    cantidad_campanas: "",
    conjuntos_activos: 0,
    facturacion_pixel: 0,
    formato_creativos: "Reel - Placas estaticas",
    producto_1_nombre: "Campera Puffer",
    producto_1_precio: 180000,
    producto_2_nombre: "Chaleco Tiffany",
    producto_2_precio: 125000,
    producto_3_nombre: "Calza Street",
    producto_3_precio: 85000,
    producto_4_nombre: "",
    producto_4_precio: null,
    producto_5_nombre: "",
    producto_5_precio: null,
    visitas_mensuales: 28550,
    canal_ml_inversion: null,
    canal_ml_no_aplica: false,
    cantidad_productos: 3,
    ml_pct_facturacion: null,
    presupuesto_diario: 0,
    absorbe_costo_envio: null,
    angulo_que_funciona: "No",
    canal_ml_cargo_fijo: null,
    canal_ml_envio_neto: null,
    canal_tienda_moneda: "ARS",
    canal_tienda_ticket: null,
    checkouts_iniciados: null,
    facturacion_mensual: 33108279,
    retencion_cupon_pct: null,
    retencion_usa_cupon: null,
    vende_mercado_libre: false,
    canal_ml_facturacion: null,
    canal_tienda_periodo: "mensual",
    carritos_abandonados: 720,
    costo_envio_promedio: 11000,
    descuento_pct_ventas: null,
    frecuencia_creativos: "1 mes",
    margen_declarado_max: null,
    margen_declarado_min: null,
    recuperacion_carrito: false,
    retargeting_abandono: false,
    canal_ml_comision_pct: null,
    mayorista_canal_usado: "",
    ml_ventas_product_ads: null,
    recompra_ventana_dias: null,
    retencion_canal_email: null,
    canal_ml_descuento_pct: null,
    canal_tienda_inversion: null,
    canal_tienda_no_aplica: false,
    consultas_por_organico: false,
    financiacion_costo_pct: null,
    mayorista_precio_lista: null,
    numeros_meta_coinciden: null,
    venta_mayorista_activa: null,
    venta_minorista_activa: null,
    canal_tienda_cargo_fijo: null,
    canal_tienda_envio_neto: null,
    csv_frecuencia_promedio: null,
    envio_cobrado_comprador: null,
    financiacion_pct_ventas: null,
    ml_productos_publicados: null,
    canal_tienda_facturacion: null,
    csv_conjuntos_bajo_gasto: null,
    mayorista_cac_por_cuenta: null,
    mayorista_costo_producto: null,
    mayorista_ticket_inicial: null,
    mayorista_tipo_comprador: "",
    ml_inversion_product_ads: null,
    recompra_tasa_actual_pct: null,
    retencion_canal_whatsapp: null,
    canal_ml_tipo_publicacion: "",
    canal_tienda_comision_pct: null,
    mayorista_cuentas_activas: null,
    mayorista_leads_mensuales: null,
    mayorista_ticket_recompra: null,
    montos_netos_de_descuento: false,
    canal_tienda_descuento_pct: null,
    mayorista_condiciones_pago: "",
    producto_1_pct_facturacion: 50,
    producto_2_pct_facturacion: 30,
    producto_3_pct_facturacion: 20,
    producto_4_pct_facturacion: null,
    producto_5_pct_facturacion: null,
    margen_declarado_confirmado: false,
    mayorista_pct_catalogo_apto: null,
    mayorista_precio_venta_real: null,
    recompra_compradores_unicos: null,
    retencion_canal_retargeting: null,
    mayorista_comision_comercial: null,
    mayorista_costo_financiacion: null,
    mayorista_impuestos_cobranza: null,
    mayorista_tiempo_cierre_dias: null,
    montos_netos_de_financiacion: false,
    canal_ml_descuento_pct_ventas: null,
    mayorista_costo_logistica_b2b: null,
    mayorista_margen_objetivo_pct: null,
    mayorista_pedido_minimo_monto: null,
    retencion_secuencia_contactos: null,
    recompra_costo_campana_mensual: null,
    recompra_ticket_segunda_compra: null,
    canal_ml_financiacion_costo_pct: null,
    mayorista_tiene_escalas_volumen: null,
    relacion_financiacion_descuento: "excluyentes",
    canal_ml_financiacion_pct_ventas: null,
    mayorista_cotizaciones_mensuales: null,
    mayorista_pedido_minimo_unidades: null,
    canal_tienda_descuento_pct_ventas: null,
    retencion_recuperacion_pct_actual: null,
    mayorista_frecuencia_recompra_dias: null,
    recompra_tiene_secuencia_postventa: null,
    canal_tienda_financiacion_costo_pct: null,
    canal_tienda_financiacion_pct_ventas: null,
    mayorista_precio_minorista_referencia: null,
    mayorista_objetivo_facturacion_mensual: null,
    mayorista_capacidad_maxima_unidades_mes: null,
    mayorista_concentracion_pct_top_cliente: null,
    mayorista_precio_visible_en_plataforma_minorista: null,
  } as DatosDiagnostico,
  derivados: {
    funnel: {
      error: null,
      estado: "combinado",
      ticket: 225226,
      compras: 147,
      exactas: {
        cr_global: 0.005148870510652518,
        p_carrito_dado_visita: null,
        p_compra_dado_checkout: null,
        p_checkout_dado_carrito: null,
      },
      visitas: 28550,
      cr_global: 0.0051,
      faltantes: ["agregados_carrito", "checkouts_iniciados"],
      desglosado: false,
      etapa_error: null,
      agregados_carrito: null,
      checkouts_iniciados: null,
      p_carrito_dado_visita: null,
      p_compra_dado_checkout: null,
      p_checkout_dado_carrito: null,
    },
    canales: [
      {
        id: "tienda_propia",
        mer: null,
        pct: null,
        estado: "ausente",
        margen: 0.639,
        ticket: 225226,
        faltantes: [],
        inversion: 0,
        envio_neto: 11000,
        roas_pauta: null,
        facturacion: null,
        comision_pais: null,
        comision_plan: null,
        margen_exacto: 0.6389902333696,
        breakeven_roas: 1.565,
        pesos_producto: [0.5, 0.3, 0.2, null, null],
        comision_origen: "benchmark_configuracion",
        componente_envio: 0.0488,
        comision_efectiva: 0.07,
        comision_vigencia: null,
        margenes_producto: [0.6589, 0.6012, 0.6459, null, null],
        comision_evidencia: "benchmark_sin_verificar",
        cargo_fijo_aplicado: false,
        comisiones_producto: [0.07, 0.07, 0.07, null, null],
        comision_provisional: true,
        cargo_fijo_disponible: null,
        inversion_publicitaria: 0,
        costo_descuento_efectivo: 0,
        margenes_producto_exactos: [0.658937945788, 0.60116016801, 0.645866050363, null, null],
        comision_escala_sospechosa: false,
        costo_financiacion_efectivo: 0,
        resultado_despues_publicidad: null,
        contribucion_antes_publicidad: null,
      },
      {
        id: "mercado_libre",
        mer: null,
        pct: null,
        estado: "ausente",
        margen: 0.5396,
        ticket: 225226,
        faltantes: [],
        inversion: null,
        envio_neto: 11000,
        roas_pauta: null,
        facturacion: null,
        comision_pais: "AR",
        comision_plan: null,
        margen_exacto: 0.5395902333696,
        breakeven_roas: 1.8533,
        pesos_producto: [0.5, 0.3, 0.2, null, null],
        comision_origen: "benchmark_provisional",
        componente_envio: 0.0488,
        comision_efectiva: 0.1694,
        comision_vigencia: null,
        margenes_producto: [0.5595, 0.5018, 0.5465, null, null],
        comision_evidencia: "benchmark_sin_verificar",
        cargo_fijo_aplicado: false,
        comisiones_producto: [0.1694, 0.1694, 0.1694, null, null],
        comision_provisional: true,
        cargo_fijo_disponible: {
          hasta: 33000,
          valor: 1095,
          fuente: "benchmark_provisional_pendiente_liquidacion",
          verificado: false,
          precio_umbral: "precio_producto",
          base_aplicacion: "pedido",
        },
        inversion_publicitaria: null,
        costo_descuento_efectivo: 0,
        margenes_producto_exactos: [0.559537945788, 0.50176016801, 0.546466050363, null, null],
        comision_escala_sospechosa: false,
        costo_financiacion_efectivo: 0,
        resultado_despues_publicidad: null,
        contribucion_antes_publicidad: null,
      },
    ],
    reserva: 0.35,
    cr_tienda: 0.0051,
    mayorista: null,
    mer_actual: null,
    cpa_objetivo: 93546,
    cpa_breakeven: 143917,
    roas_objetivo: 2.41,
    breakeven_roas: 1.565,
    delta_medicion: null,
    margen_muestra: 0.639,
    pesos_producto: [0.5, 0.3, 0.2, null, null],
    canal_principal: null,
    cr_umbral_verde: 0.007,
    mer_marketplace: null,
    componente_envio: 0.0488,
    roas_product_ads: null,
    cobertura_canales: 0,
    comision_pasarela: 0.05,
    margenes_producto: [0.6589, 0.6012, 0.6459, null, null],
    mer_tienda_propia: null,
    pedidos_mensuales: 147,
    pedidos_semanales: 34.2,
    volumen_suficiente: false,
    cobertura_productos: 100,
    comision_plataforma: 0.02,
    envio_neto_vendedor: 11000,
    margen_contribucion: 0.639,
    contradiccion_margen: null,
    presupuesto_arranque: {
      confianza: "media",
      supuestos: [
        "CPA objetivo calculado con una reserva de 35% sobre el breakeven.",
        "50 conversiones por semana para que un conjunto salga de aprendizaje (heurística de Meta).",
        "Costo por evento intermedio estimado en 20% del CPA objetivo (benchmark de configuración, sin verificar con datos reales de este cliente).",
        "Rango de incertidumbre de ±20% al no contar con historial propio de costo por evento intermedio.",
      ],
      piso_teorico_compra: 20112431,
      arranque_evento_intermedio: { alto: 4826983, bajo: 3217989 },
    },
    conjuntos_sostenibles: 0,
    contribucion_marginal: 21155867,
    costo_descuento_efectivo: 0,
    inversion_actual_mensual: 0,
    piso_mensual_un_conjunto: 20112431,
    piso_semanal_por_conjunto: 4677309,
    hay_inversion_publicitaria: false,
    costo_financiacion_efectivo: 0,
    inversion_publicitaria_total: 0,
  } as unknown as Derivados,
  fugas: [
    {
      id: "funnel_combinado",
      tipo: "monto",
      monto: 423117,
      detalle:
        "Faltan las etapas intermedias del funnel, así que la oportunidad no se puede repartir entre navegación, carrito y checkout. Se calcula una sola sobre visitas y compras, con la conversión global observada.",
      etiqueta: "Oportunidad de funnel (sin desglose)",
      impactos: [
        {
          tipo: "facturacion_incremental",
          moneda: "ARS",
          periodo: "mensual",
          confianza: "media",
          dependencias: ["ticket_promedio"],
          montoMensual: 662166,
        },
        {
          tipo: "contribucion_incremental",
          moneda: "ARS",
          periodo: "mensual",
          confianza: "media",
          dependencias: ["ticket_promedio", "margen_contribucion"],
          montoMensual: 423118,
        },
      ],
      confianza: "parcial",
      faltantes: ["agregados_carrito", "checkouts_iniciados"],
      calculable: true,
      usa_margen: true,
    },
    {
      id: "recuperacion_carrito",
      tipo: "monto",
      monto: null,
      etiqueta: "Recuperación de carritos abandonados",
      impactos: [
        {
          tipo: "contribucion_incremental",
          moneda: "ARS",
          periodo: "mensual",
          confianza: "retenida",
          dependencias: ["retencion_recuperacion_pct_actual"],
          montoMensual: null,
          motivoRetencion: "No se pudo calcular la recuperación de carrito con los datos actuales.",
        },
      ],
      faltantes: ["retencion_recuperacion_pct_actual"],
      calculable: false,
      usa_margen: true,
    },
  ] as unknown as Fuga[],
};
