/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedDiagnosticosIdRouteImport } from './routes/_authenticated/diagnosticos.$id'
import { Route as AuthenticatedDiagnosticosNuevoRouteImport } from './routes/_authenticated/diagnosticos.nuevo'

const AuthenticatedDiagnosticosIdRoute =
  AuthenticatedDiagnosticosIdRouteImport.update({
    id: '/_authenticated/diagnosticos/$id',
    path: '/diagnosticos/$id',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedDiagnosticosNuevoRoute =
  AuthenticatedDiagnosticosNuevoRouteImport.update({
    id: '/_authenticated/diagnosticos/nuevo',
    path: '/diagnosticos/nuevo',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/diagnosticos/$id': typeof AuthenticatedDiagnosticosIdRoute
  '/diagnosticos/nuevo': typeof AuthenticatedDiagnosticosNuevoRoute
}
export interface FileRoutesByTo {
  '/diagnosticos/$id': typeof AuthenticatedDiagnosticosIdRoute
  '/diagnosticos/nuevo': typeof AuthenticatedDiagnosticosNuevoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated/diagnosticos/$id': typeof AuthenticatedDiagnosticosIdRoute
  '/_authenticated/diagnosticos/nuevo': typeof AuthenticatedDiagnosticosNuevoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/diagnosticos/$id' | '/diagnosticos/nuevo'
  fileRoutesByTo: FileRoutesByTo
  to: '/diagnosticos/$id' | '/diagnosticos/nuevo'
  id:
    | '__root__'
    | '/_authenticated/diagnosticos/$id'
    | '/_authenticated/diagnosticos/nuevo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedDiagnosticosIdRoute: typeof AuthenticatedDiagnosticosIdRoute
  AuthenticatedDiagnosticosNuevoRoute: typeof AuthenticatedDiagnosticosNuevoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated/diagnosticos/$id': {
      id: '/_authenticated/diagnosticos/$id'
      path: '/diagnosticos/$id'
      fullPath: '/diagnosticos/$id'
      preLoaderRoute: typeof AuthenticatedDiagnosticosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/diagnosticos/nuevo': {
      id: '/_authenticated/diagnosticos/nuevo'
      path: '/diagnosticos/nuevo'
      fullPath: '/diagnosticos/nuevo'
      preLoaderRoute: typeof AuthenticatedDiagnosticosNuevoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedDiagnosticosIdRoute: AuthenticatedDiagnosticosIdRoute,
  AuthenticatedDiagnosticosNuevoRoute: AuthenticatedDiagnosticosNuevoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
