/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedDiagnosticosIdRouteImport } from './routes/_authenticated/diagnosticos.$id'
import { Route as AuthenticatedDiagnosticosNuevoRouteImport } from './routes/_authenticated/diagnosticos.nuevo'
import { Route as AuthenticatedDocumentosIdSlugRouteImport } from './routes/_authenticated/documentos.$id.$slug'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDiagnosticosIdRoute =
  AuthenticatedDiagnosticosIdRouteImport.update({
    id: '/diagnosticos/$id',
    path: '/diagnosticos/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDiagnosticosNuevoRoute =
  AuthenticatedDiagnosticosNuevoRouteImport.update({
    id: '/diagnosticos/nuevo',
    path: '/diagnosticos/nuevo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDocumentosIdSlugRoute =
  AuthenticatedDocumentosIdSlugRouteImport.update({
    id: '/documentos/$id/$slug',
    path: '/documentos/$id/$slug',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/diagnosticos/$id': typeof AuthenticatedDiagnosticosIdRoute
  '/diagnosticos/nuevo': typeof AuthenticatedDiagnosticosNuevoRoute
  '/documentos/$id/$slug': typeof AuthenticatedDocumentosIdSlugRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/': typeof AuthenticatedIndexRoute
  '/diagnosticos/$id': typeof AuthenticatedDiagnosticosIdRoute
  '/diagnosticos/nuevo': typeof AuthenticatedDiagnosticosNuevoRoute
  '/documentos/$id/$slug': typeof AuthenticatedDocumentosIdSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/diagnosticos/$id': typeof AuthenticatedDiagnosticosIdRoute
  '/_authenticated/diagnosticos/nuevo': typeof AuthenticatedDiagnosticosNuevoRoute
  '/_authenticated/documentos/$id/$slug': typeof AuthenticatedDocumentosIdSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/diagnosticos/$id'
    | '/diagnosticos/nuevo'
    | '/documentos/$id/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/'
    | '/diagnosticos/$id'
    | '/diagnosticos/nuevo'
    | '/documentos/$id/$slug'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/'
    | '/_authenticated/diagnosticos/$id'
    | '/_authenticated/diagnosticos/nuevo'
    | '/_authenticated/documentos/$id/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/diagnosticos/$id': {
      id: '/_authenticated/diagnosticos/$id'
      path: '/diagnosticos/$id'
      fullPath: '/diagnosticos/$id'
      preLoaderRoute: typeof AuthenticatedDiagnosticosIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/diagnosticos/nuevo': {
      id: '/_authenticated/diagnosticos/nuevo'
      path: '/diagnosticos/nuevo'
      fullPath: '/diagnosticos/nuevo'
      preLoaderRoute: typeof AuthenticatedDiagnosticosNuevoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documentos/$id/$slug': {
      id: '/_authenticated/documentos/$id/$slug'
      path: '/documentos/$id/$slug'
      fullPath: '/documentos/$id/$slug'
      preLoaderRoute: typeof AuthenticatedDocumentosIdSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedDiagnosticosIdRoute: typeof AuthenticatedDiagnosticosIdRoute
  AuthenticatedDiagnosticosNuevoRoute: typeof AuthenticatedDiagnosticosNuevoRoute
  AuthenticatedDocumentosIdSlugRoute: typeof AuthenticatedDocumentosIdSlugRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedDiagnosticosIdRoute: AuthenticatedDiagnosticosIdRoute,
  AuthenticatedDiagnosticosNuevoRoute: AuthenticatedDiagnosticosNuevoRoute,
  AuthenticatedDocumentosIdSlugRoute: AuthenticatedDocumentosIdSlugRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
